var data = {
  'pilot': {
      features:'Pilot is a good family car',
      price:"Pilot starting MSRP is $30,145. For more detailed pricing, please configure your dream vehicle at http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=Pilot&ModelYear=2016",
      safety:"Safety features include a rearview camera, Honda Sensing, LED daytime running lights and a security system.",
      seats:"Pilot can fit up to 8 people." ,
      mileage:"The MPG is 27 highway and 19 city. ",
      photos:"http://automobiles.honda.com/pilot/photo-tour.aspx",
      drive:"It comes with both 2WD and AWD and is available with 6-speed or 9-speed automatic transmission.",
      standard:"Pilot comes standard with a 280-hp 3.5-liter V6 engine, rearview camera, and push button start.",
      audio:"The audio system can have up to 10 speakers and pump out 540 watts.",
      overview:"The Pilot can seat up to 8 so it’s perfect for families. It’s also great for long road trips and outdoor adventures.",
      offers:"If you are a recent or soon-to-be college graduate, we know that you are embarking on a new phase of your life, and that phase may include a new vehicle! To reward your hard work, Honda would like to give you $500 toward any new 2015 or 2016 model year Honda automobile when you finance or lease with Honda Financial ServicesSM"
        },
    'civic coupe': {
      features: 'The Civic Coupe is a sporty compact coupe with good mileage.',
      price:"Starting MSRP is $19,050.For more detailed pricing, please configure your dream car at  http://automobiles.honda.com/civic-coupe ",
      safety:"Safety features include a rearview camera and Honda Sensing.",
      seats:"Civic can fit up to 5 people" ,
      mileage:"The MPG is 38 highway and 26 city",
      drive:"You can get either a 6-speed manual or CVT",
      standard:"Civic Coupe comes standard with rearview camera, automatic climate control, 16-inch alloy wheels and LED daytime running lights and taillights",
      photos:"http://automobiles.honda.com/civic-sedan/photo-tour.aspx",
      audio:"The audio system features up to 10 speakers and pumps out 450 watts.",
      overview:"The Civic Coupe is a sporty compact coupe with good mileage.",
      offers:"$259 per month for 36 months"
        },
      'civic sedan': {
      features: 'civic is compact car',
      price:"Starting MSRP is $18,640.For more detailed pricing, please configure your dream car at  http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=Civic%20Sedan&ModelYear=2016",
      safety:"Safety features include rearview camera, security system and Honda Sensing.",
      seats:"Civic seats 5 people" ,
      mileage:"The MPG is 42 highway and 31 city.",
      drive:"You can get either a 6-speed manual or CVT.",
      standard:"The Civic Sedan comes standard with 158-hp 2-liter 4-cylinder engine, electric parking brake, rearview camera, Bluetooth, and LED daytime running lights.",
      photos:"http://automobiles.honda.com/civic-sedan/photo-tour.aspx",
      audio:"The audio system features up to 10 speakers and pumps out 450 watts.",
      overview:"The Civic Sedan offers a comfortable, reliable ride. Great for commuters or small families.",
      offers:"$259 per month for 36 months"
        }, 
       'civic hybrid': {
      features: 'The Civic Hybrid has a combined MPG of 45 and has eco-friendly features like coaching bars to help you drive more efficiently and an Econ button you can push when you want to maximize fuel efficiency.',
      price:"Starting MSRP is $24,735.For more detailed pricing, please configure your dream car at  http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=Civic%20Hybrid&ModelYear=2015",
      safety:"Safety features include rearview camera, forward collision warning and lane departure warning.",
      seats:"It seats 5 people" ,
      mileage:"The MPG is 47 highway and 44 city. ",
      drive:"The Hybrid has a continuously variable transmission (CVT).",
      standard:"The Civic Sedan comes standard with Lithium-Ion battery and Eco Assist, which helps you drive more efficiently. ",
      photos:"http://automobiles.honda.com/civic-hybrid/exterior-photos.aspx",
      audio:"The hybrid comes with a 160-watt AM/FM/CD audio system with 6 speakers.",
      overview:"The Civic Hybrid is a great pick for commuters or small families who need a fuel-efficient car.",
      offers:"$259 per month for 36 months"
        },  
     'accord coupe': {
      features: 'The Accord Coupe is a sporty option. It has an available 278 horsepower V6 engine that makes hitting the road and hugging the curves more fun.',
      price:"Starting MSRP is $23,875.For more detailed pricing, please configure your dream car at  http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=Accord%20Coupe&ModelYear=2016",
      safety:"The Accord Coupe features a rearview camera and security system as well as Honda Sensing and Honda LaneWatch technology.",
      seats:"It can seat up to 5 people" ,
      mileage:"The MPG is 35 highway and 26 city.",
      photos:"http://automobiles.honda.com/accord-coupe/photo-tour.aspx",
      drive:"You can get either a 6-speed manual or CVT",
      standard:"The Accord Coupe comes standard with a 185-hp 4-cylinder engine, 17” alloy wheels, rearview camera and Bluetooth streaming audio.",
      audio:"It comes with a 360-watt AM FM CD audio system with 7 speakers.",
      overview:"The Accord Coupe is a sporty option. It has an available 278 horsepower V6 engine that makes hitting the road and hugging the curves more fun.",
      offers:"If you are a recent or soon-to-be college graduate, we know that you are embarking on a new phase of your life, and that phase may include a new vehicle! To reward your hard work, Honda would like to give you $500 toward any new 2015 or 2016 model year Honda automobile when you finance or lease with Honda Financial ServicesSM"
        },
     'accord sedan': {
      features: 'A reliable, efficient, versatile mid-size sedan.',
      price:"Starting MSRP is $22,205.For more detailed pricing, please configure your dream car at  http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=Accord%20Sedan&ModelYear=2016",
      safety:"comes with multi angle rearview camera and honda sensing technologies",
      seats:" seats 5 people" ,
      mileage:"The MPG is 37 highway and 27 city.",
      drive:"comes with both 2WD and AWD",
      standard:"A 185-hp 2.4-liter four and a six-speed manual are standard in both the coupe and sedan",
      photos:"http://automobiles.honda.com/accord-sedan/photo-tour.aspx",
      audio:"The audio system features 180 watt AM FM CD audio system with 6 speakers",
      overview:"A reliable, efficient, versatile mid-size sedan. The Accord has landed on Car and Driver's Top Ten List for the last 30 years.",
      offers:"$259 per month for 36 months"
        },
      'cr-v': {
      features: 'This compact SUV works for small families or for outdoor adventurers who like to travel light.',
      price:"Starting MSRP is $23,745.For more detailed pricing, please configure your dream car at  http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=CR-V&ModelYear=2016",
      safety:"comes with multi angle rearview camera and honda sensing technologies",
      seats:"seats 5 people" ,
      mileage:"The MPG is 33 highway and 26 city.",
      photos:"http://automobiles.honda.com/cr-v/photo-tour.aspx",
      drive:"comes with both 2WD and AWD",
      standard:"lx comes with moonroof, key less entry, ex comes with push button",
      audio:"The audio system features 180 watt AM FM CD audio system with 6 speakers",
      overview:"This compact SUV works for small families or for outdoor adventurers who like to travel light.",
      offers:"If you are a recent or soon-to-be college graduate, we know that you are embarking on a new phase of your life, and that phase may include a new vehicle! To reward your hard work, Honda would like to give you $500 toward any new 2015 or 2016 model year Honda automobile when you finance or lease with Honda Financial ServicesSM"
        },
     'cr-z': {
      features: "A sporty hybrid that's both efficient and fun.",
      price:"Starting MSRP is $20,295.For more detailed pricing, please configure your dream car at http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=CR-Z&ModelYear=2016",
      safety:"comes with backup camera and Honda lanewatch",
      seats:" seats 5 people" ,
      mileage:"38 on highway and 28 on city roads ",
      drive:"comes with both 2WD ",
      standard:"lx comes with moonroof, key less entry, ex comes with push button",
      photos:"http://automobiles.honda.com/cr-z/photo-tour.aspx",
      audio:"The audio system features 180 watt AM FM CD audio system with 6 speakers",
      overview:"A sporty hybrid that's both efficient and fun.",
      offers:"$259 per month for 36 months"
        },
      'fit': {
      features: 'Fit is a fun car',
      price:"Starting MSRP is $15,890.For more detailed pricing, please configure your dream car at http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=Fit&ModelYear=2016",
      safety:"Fit comes with back up camera and honda sensing technologies",
      seats:"Fit has seating for 5" ,
      mileage:"The MPG is 41 highway and 33 city.",
      photos:"http://automobiles.honda.com/Fit/photo-tour.aspx",
      drive:"comes with both 2WD",
      standard:"lx comes with moonroof, key less entry, ex comes with push button",
      audio:"The  audio system features 180 watt AM FM CD audio system with 6 speakers",
      overview:"The Fit is small enough to squeeze into tight spaces, but big enough inside to fit you and a surprising amount of cargo.",
      offers:"If you are a recent or soon-to-be college graduate, we know that you are embarking on a new phase of your life, and that phase may include a new vehicle! To reward your hard work, Honda would like to give you $500 toward any new 2015 or 2016 model year Honda automobile when you finance or lease with Honda Financial ServicesSM"
        },
     'hr-v': {
      features: 'The HR-V mixes angles and curves in an attractive design that lends it a sporty look',
      price:"HR-V starting MSRP is $19,215.For more detailed pricing, please configure your dream car at http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=HR-V&ModelYear=2016",
      safety:"comes with rearview camera and security system",
      seats:"seats 5 people" ,
      mileage:"The MPG is 28 highway and 19 city.",
      drive:"Comes with both 2WD and AWD",
      standard:"HR-V LX comes standard with Multi-Angle Rearview Camera,60/40 Split 2nd-Row Magic Seat and remote entry.",
      photos:"http://automobiles.honda.com/HR-V/photo-tour.aspx",
      audio:"features 160 watt AM FM CD audio system with 4 speaker",
      overview:"Compact on the outside, roomy on the inside, the HR-V gives you the feel of an SUV in a smaller, versatile package.",
      offers:"$259 per month for 36 months"
        },
      'odyssey': {
      features: 'The Odyssey has charmed customers for years with its unrivaled road manners, smooth powertrain, and accommodating interior. With room for up to eight passengers to sit comfortably, the Odyssey is also fuel-efficient, thanks to the cylinder-deactivation feature on its 248-hp 3.5-liter V-6. Perhaps most exciting is the built-in vacuum in the cargo area.',
      price:"Odyssey starting MSRP is $29,400.For more detailed pricing, please configure your dream car at http://automobiles.honda.com/tools/build-price/trims.aspx?ModelID=&ModelName=Odyssey&ModelYear=2016",
      safety:"Odyssey comes with Honda LaneWatch™, Blind Spot Information System and rearview camera.",
      seats:"Odyessey has seating for up to 8 " ,
      mileage:"The MPG is 28 highway and 19 city. ",
      drive:"comes with both 2WD",
      standard:"Odyssey LX comes standard with Rearview Camera with Guidelines, 8-Inch Multi-Information Display, Bluetooth,ABS, One-Motion 60/40 Split 3rd-Row Magic Seat®,USB and Child-Proof Rear Door Locks.",
      photos:"http://automobiles.honda.com/odyssey/photo-tour.aspx",
      audio:"The odyssey audio system features up to 7 speakers and pumps out 270 watts.",
      overview:"The Odyssey seats 8 comfortably, which makes it the perfect minivan to shuttle the family around in style.",
      offers:"$259 per month for 36 months"
        }
};

var general = {
      'honda sensing': 'Honda Sensing™ is a suite of safety and driver assistive-technologies designed to help keep you out of bad situations by alerting you to things you might miss while driving.1 (Pilot EX)',
      'small car': "Fit is our best small car",
      'fuel efficient':"So that would be our Civic Hybrid",
      'greet':"I can help you with questions about Honda Cars",
      'family car':"Great. I’d recommend the Pilot. It seats 8 and has great safety ratings.",
      'SUV' :"For an SUV, I’d recommend the Pilot. It seats 8 and has great safety ratings.",
      'small SUV':"CR-V would be more your style. It seats 5 and still has lots of cargo space and great safety features.",
      'eco assist': "Eco Assist is a dashboard feature that displays colored coaching bars that show you how efficiently you’re driving.",
      'honda lanewatch':"With Honda LaneWatch™, anytime you signal right before changing lanes, a small camera on the passenger side mirror will turn on and display live video on your 8-Inch Display Audio touchscreen, revealing nearly ",
      
      };

